name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (site)
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v1
