name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches: [master] # change to main if you use main

concurrency:
  group: gh-pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --clean

      - name: Show built site files (debug)
        run: |
          if [ -d "./site" ]; then
            echo "site/ exists — contents:"
            ls -la ./site || true
          else
            echo "site/ directory missing!"
            exit 1
          fi

      - name: "Debug: GET Pages site (API)"
        run: |
          echo "Calling Pages API for repo $GITHUB_REPOSITORY"
          curl -i -sS \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pages" || true

      - name: Configure Pages (allow creation if missing)
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enablement: true

      - name: Upload artifact (site) for Pages (v4)
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages (v4)
        uses: actions/deploy-pages@v4
